# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/C++.gitlab-ci.yml

# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/

#+++++++++++-+-+--+----- --- -- -  -  -   -
# TODO [tastolfi 2022-04-14] Use the GitLab registry once we sort out login auth reliability.
#
# image: registry.insidelabs-git.mathworks.com/tastolfi/batteries:latest
image: ah-tastolfi-l.dhcp.mathworks.com:5000/a8-ubuntu:latest
#
#+++++++++++-+-+--+----- --- -- -  -  -   -

default:
  retry:
    max: 2
    when: runner_system_failure

stages:
  - install
  - build
  - test

install:
  stage: install
  script:
    - script/ci-make.sh install
  rules:
    - changes:
      - conanfile.py
      - .gitlab-ci.yml
  cache:
    - key: conan-cache
      paths:
        - .conan/
      policy: push
    - key: build-cache
      paths:
        - build/
      policy: push

build:
  stage: build
  script:
    - script/ci-make.sh build
  artifacts:
    paths:
      - build/
  cache:
    - key: conan-cache
      paths:
        - .conan/
      policy: pull
    - key: build-cache
      paths:
        - build/
      policy: pull-push

test:
  stage: test
  script:
    - script/ci-make.sh test
  cache:
    - key: conan-cache
      paths:
        - .conan/
      policy: pull
    - key: build-cache
      paths:
        - build/
      policy: pull
