#+++++++++++-+-+--+----- --- -- -  -  -   -
# See batteries/docker/Dockerfile
#
image: registry.gitlab.com/tonyastolfi/batteries:latest

#+++++++++++-+-+--+----- --- -- -  -  -   -
default:
  retry:
    max: 2
    when: runner_system_failure

#+++++++++++-+-+--+----- --- -- -  -  -   -
stages:
  - debug_env
  - install
  - build
  - test
  - release

debug_env:
  stage: debug_env
  variables:
    RELEASE_CONAN_LOGIN_USERNAME: "${CI_DEPLOY_USER}"
    RELEASE_CONAN_PASSWORD: "${CI_DEPLOY_PASSWORD}"
  script:
    - echo "CI_DEPLOY_USER=${CI_DEPLOY_USER}"
    - echo "CI_DEPLOY_PASSWORD=${CI_DEPLOY_PASSWORD}"
    - env

#+++++++++++-+-+--+----- --- -- -  -  -   -
install:
  stage: install
  script:
    - script/ci-make.sh install
  rules:
    - changes:
      - conanfile.py
      - .gitlab-ci.yml
  cache:
    - key: conan-cache
      paths:
        - .conan/
      policy: push
    - key: build-cache
      paths:
        - build/
      policy: push

#+++++++++++-+-+--+----- --- -- -  -  -   -
build:
  stage: build
  script:
    - script/ci-make.sh build
  artifacts:
    paths:
      - build/
  cache:
    - key: conan-cache
      paths:
        - .conan/
      policy: pull
    - key: build-cache
      paths:
        - build/
      policy: pull-push

#+++++++++++-+-+--+----- --- -- -  -  -   -
test:
  stage: test
  script:
    - script/ci-make.sh test
  artifacts:
    reports:
      junit:
        - build/Release/test-results.xml
        - build/Release/death-test-results.xml
  cache:
    - key: conan-cache
      paths:
        - .conan/
      policy: pull
    - key: build-cache
      paths:
        - build/
      policy: pull

#+++++++++++-+-+--+----- --- -- -  -  -   -
release:
  stage: release
  script:
    - script/publish-release.sh
  rules:
    - if: $CI_COMMIT_TAG
  cache:
    - key: conan-cache
      paths:
        - .conan/
      policy: pull
    - key: build-cache
      paths:
        - build/
      policy: pull
