#+++++++++++-+-+--+----- --- -- -  -  -   -
# See batteries/docker/Dockerfile
#
image: registry.gitlab.com/batteriescpp/batteries:latest.linux_gcc11_amd64

#+++++++++++-+-+--+----- --- -- -  -  -   -
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG

#+++++++++++-+-+--+----- --- -- -  -  -   -
default:
  retry:
    max: 2
    when: runner_system_failure
  before_script:
    - "test -d /local/gitlab-runner-local-cache || { echo \"FATAL: no local docker cache volume mapped\"; false; }"
    - "if [ ! -d /local/gitlab-runner-local-cache/.conan ]; then rm -rf /local/gitlab-runner-local-cache/.conan.IN_PROGRESS && cp -r ~/.conan /local/gitlab-runner-local-cache/.conan.IN_PROGRESS && mv /local/gitlab-runner-local-cache/.conan.IN_PROGRESS /local/gitlab-runner-local-cache/.conan; fi"
    - "if [ ~/.conan/settings.yml -nt /local/gitlab-runner-local-cache/.conan/settings.yml ]; then cp ~/.conan/settings.yml  /local/gitlab-runner-local-cache/.conan/settings.yml; fi"
    - export CONAN_USER_HOME=/local/gitlab-runner-local-cache
    - echo "CI_DEPLOY_USER=${CI_DEPLOY_USER}"
    - echo "CI_DEPLOY_PASSWORD=${CI_DEPLOY_PASSWORD}"

#+++++++++++-+-+--+----- --- -- -  -  -   -
stages:
  - install
  - build
  - test
  - release


#=#=#==#==#===============+=+=+=+=++=++++++++++++++-++-+--+-+----+---------------
# Install Stage

#+++++++++++-+-+--+----- --- -- -  -  -   -
install.linux_gcc9_amd64:
  image: registry.gitlab.com/batteriescpp/batteries:latest.linux_gcc9_amd64
  stage: install
  script:
    - echo "CONAN_USER_HOME=${CONAN_USER_HOME}"
    - make BUILD_TYPE=Release install
  rules:
    - changes:
      - conanfile.py
      - .gitlab-ci.yml
      - script/*

#+++++++++++-+-+--+----- --- -- -  -  -   -
install.linux_gcc11_amd64:
  image: registry.gitlab.com/batteriescpp/batteries:latest.linux_gcc11_amd64
  stage: install
  script:
    - echo "CONAN_USER_HOME=${CONAN_USER_HOME}"
    - conan --version
    - make BUILD_TYPE=Release install
  rules:
    - changes:
      - conanfile.py
      - .gitlab-ci.yml
      - script/*

#=#=#==#==#===============+=+=+=+=++=++++++++++++++-++-+--+-+----+---------------
# Build Stage

#+++++++++++-+-+--+----- --- -- -  -  -   -
build.linux_gcc9_amd64:
  image: registry.gitlab.com/batteriescpp/batteries:latest.linux_gcc9_amd64
  stage: build
  needs: [install.linux_gcc9_amd64]
  script:
    - echo "CONAN_USER_HOME=${CONAN_USER_HOME}"
    - make BUILD_TYPE=Release build
  artifacts:
    paths:
      - build/
    exclude:
      - build/**/*.o
      - build/**/*.d
      - build/**/*.obj

#+++++++++++-+-+--+----- --- -- -  -  -   -
build.linux_gcc11_amd64:
  image: registry.gitlab.com/batteriescpp/batteries:latest.linux_gcc11_amd64
  stage: build
  needs: [install.linux_gcc11_amd64]
  script:
    - echo "CONAN_USER_HOME=${CONAN_USER_HOME}"
    - make BUILD_TYPE=Release build
  artifacts:
    paths:
      - build/
    exclude:
      - build/**/*.o
      - build/**/*.d
      - build/**/*.obj

#=#=#==#==#===============+=+=+=+=++=++++++++++++++-++-+--+-+----+---------------
# Test Stage

#+++++++++++-+-+--+----- --- -- -  -  -   -
test.linux_gcc9_amd64:
  image: registry.gitlab.com/batteriescpp/batteries:latest.linux_gcc9_amd64
  stage: test
  needs: [build.linux_gcc9_amd64]
  script:
    - echo "CONAN_USER_HOME=${CONAN_USER_HOME}"
    - make BUILD_TYPE=Release test
  artifacts:
    reports:
      junit:
        - build/Release/test-results.xml
        - build/Release/death-test-results.xml

#+++++++++++-+-+--+----- --- -- -  -  -   -
test.linux_gcc11_amd64:
  image: registry.gitlab.com/batteriescpp/batteries:latest.linux_gcc11_amd64
  stage: test
  needs: [build.linux_gcc11_amd64]
  script:
    - echo "CONAN_USER_HOME=${CONAN_USER_HOME}"
    - make BUILD_TYPE=Release test
  artifacts:
    reports:
      junit:
        - build/Release/test-results.xml
        - build/Release/death-test-results.xml

#=#=#==#==#===============+=+=+=+=++=++++++++++++++-++-+--+-+----+---------------
# Release Stage

#+++++++++++-+-+--+----- --- -- -  -  -   -
# Because this project is header-only, we only run release on one platform.
#
release:
  image: registry.gitlab.com/batteriescpp/batteries:latest.linux_gcc11_amd64
  stage: release
  needs:
    - job: test.linux_gcc9_amd64
      artifacts: false
    - job: test.linux_gcc11_amd64
      artifacts: true
  variables:
    RELEASE_CONAN_LOGIN_USERNAME: "${CI_DEPLOY_USER}"
    RELEASE_CONAN_PASSWORD: "${CI_DEPLOY_PASSWORD}"
  script:
    - env | grep 'RELEASE_CONAN'
    - env | grep -v 'RELEASE_CONAN'
    - script/publish-release.sh
  release:
    tag_name: ${CI_COMMIT_TAG}
    description: $CI_COMMIT_MESSAGE
  rules:
    - if: $CI_COMMIT_TAG

#+++++++++++-+-+--+----- --- -- -  -  -   -
# Make sure that doc generation doesn't happen until all tests have passed, but
# only use the artifacts from linux_gcc11_amd64.
#
docs:
  stage: release
  needs:
    - job: test.linux_gcc9_amd64
      artifacts: false
    - job: test.linux_gcc11_amd64
      artifacts: true
  script:
    - make deploy-docs
  rules:
    - if: $CI_COMMIT_TAG
