# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/C++.gitlab-ci.yml

# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/

image: ah-tastolfi-l.dhcp.mathworks.com:5000/a8-ubuntu:latest
#image: registry.insidelabs-git.mathworks.com/tastolfi/batteries:latest

default:
  cache:
    - key: conan-cache
      paths:
        - .conan/
    - key: build-cache
      paths:
        - build/
  artifacts:
    paths:
      - build/
    
  retry:
    max: 2
    when: runner_system_failure

stages:
  - install
  - build
  - test

install:
  stage: install
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  # before_script:
  #   - apt update && apt -y install make autoconf
  script:
    - cp -r /root/.conan ./ && CONAN_USER_HOME=$(pwd) make install
  rules:
    - changes:
      - conanfile.py
      - .gitlab-ci.yml

build:
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  # before_script:
  #   - apt update && apt -y install make autoconf
  script:
    - cp -r /root/.conan ./ && CONAN_USER_HOME=$(pwd) make build

# run tests using the binary built before
test:
  stage: test
  script:
    - cp -r /root/.conan ./ && CONAN_USER_HOME=$(pwd) make test
