#pragma once
#ifndef BATTERIES_ASYNC_SINGLE_THREAD_EXECUTOR_HPP
#define BATTERIES_ASYNC_SINGLE_THREAD_EXECUTOR_HPP

namespace batteries {

}  // namespace batteries

#endif  // BATTERIES_ASYNC_SINGLE_THREAD_EXECUTOR_HPP
