site_name: Batteries C++
theme:
  name: material
  custom_dir: overrides
extra_css:
  - stylesheets/extra.css
nav:
  - Home: index.md
  - Headers:
    - batteries/assert.hpp: /assert.hpp
    - batteries/async/*: /async
    - batteries/case_of.hpp: /case_of.hpp
    - batteries/cpu_align.hpp: /cpu_align.hpp
    - batteries/seq.hpp: /seq
    - batteries/status.hpp: /status.hpp
  - Reference:
    - Files: /_autogen/Files/
    - Classes: /_autogen/Classes/
markdown_extensions:
  - toc:
      permalink: "&#128279;"
      toc_depth: "2-4"
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - search
  - autorefs
