// Convenience header to include all of the Batteries library.
//
#pragma once

#include "batteries/assert.hpp"
#include "batteries/case_of.hpp"
#include "batteries/checked_cast.hpp"
#include "batteries/cpu_align.hpp"
#include "batteries/finally.hpp"
#include "batteries/hint.hpp"
#include "batteries/int_types.hpp"
#include "batteries/nullable.hpp"
#include "batteries/radix_queue.hpp"
#include "batteries/segv.hpp"
#include "batteries/small_fn.hpp"
#include "batteries/state_machine_model.hpp"
#include "batteries/static_assert.hpp"
#include "batteries/static_dispatch.hpp"
#include "batteries/stream_util.hpp"
#include "batteries/strict.hpp"
#include "batteries/strong_typedef.hpp"
#include "batteries/suppress.hpp"
#include "batteries/tuples.hpp"
#include "batteries/type_traits.hpp"
#include "batteries/utility.hpp"
#include "batteries/var_size_array.hpp"
